spring:
  application:
    name: "processing"
  config:
    import: 'file:config/config.yml,classpath:application-domain.yml'
  threads:
    virtual:
      enabled: true
  mvc:
    problem-details:
      enabled: true