spring:
  datasource:
    username:
    password:
    url:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
      client:
        registration:
          keycloak-bff:
            provider: keycloak-provider
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            scope: openid,profile
        provider:
          keycloak-provider:
            issuer-uri:
  kafka:
    bootstrap-servers:
cache:
  ttl:
    client-get-seconds: 3600
kafka:
  group-id:
  topic:
    merchant-details:
      callback: