cache:
  ttl:
    client-get-seconds:
secrets:
  master-key: # мастер ключ 32 байта, для генерации можно использовать openssl rand -base64 32
  jwt:
    private:  # путь к файлу приватного ключа
    public: # путь к фалу публичного ключа
    ttl-seconds:
    version:
    refresh-ttl-seconds:
kafka:
  group-id:
  topic:
    merchant-details:
      callback: