spring:
  grpc:
    client:
      channels:
        api-clients:
          address: ""
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5000
      server:
        webflux:
          routes:
            - id: clients-login-route
              uri: https://api-clients-service
              predicates:
                - Path=/api-clients/login

            - id: clients-secured-route
              uri: https://api-clients-service
              predicates:
                - Path=/api-clients/**
              filters:
                - JwtAuthFilter

            - id: billing-secured-route
              uri: https://billing-service
              predicates:
                - Path=/billing/**
              filters:
                - JwtAuthFilter

            - id: orders-secured-route
              uri: https://orders-service
              predicates:
                - Path=/orders/**
              filters:
                - JwtAuthFilter

            - id: details-api-route
              uri: https://details-api-service
              predicates:
                - Path=/api/**
