syntax = "proto3";

option java_package = "net.rcetech.grpc.generated";
option java_multiple_files = true;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";

service ClientsService {
  /**
  * Метод получения клиента по апи ключу.
  * При отсутствии клиента возвращает gRPC-код NOT_FOUND_VALUE (Код 5).
  * При отсутствии/невалидности переданного ключа ключа возвращает gRPC-код INVALID_ARGUMENT (Код 3).
  */
  rpc GetClientByApiKey (GetClientByApiKeyGrpc) returns (GetClientByApiKeyResponseGrpc);

}

message GetClientByApiKeyGrpc {
  string api_key = 1 [(buf.validate.field).string.min_len = 1];
}

message GetClientByApiKeyResponseGrpc {
  string username = 1;
  string secret = 2;
  string status = 3;
}

