plugins {
    id 'processing'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'

    compileOnly 'jakarta.annotation:jakarta.annotation-api:3.0.0'
}

bootJar {
    enabled = false
}