plugins {
    id 'processing'
    id 'com.google.protobuf'
}

dependencies {
    testImplementation project(':processing-app')

    testImplementation 'org.testcontainers:testcontainers-mysql'
    testImplementation 'org.testcontainers:testcontainers-kafka'
    testImplementation 'com.github.dasniko:testcontainers-keycloak:3.5.0'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:junit-jupiter:1.21.4'

    testImplementation 'org.springframework.boot:spring-boot-resttestclient:4.1.0'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    testImplementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
}

bootJar {
    enabled = false
}