plugins {
    id 'processing'
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':gateway-api')


}

tasks.named('bootJar') {
    archiveFileName = 'processing.jar'
    destinationDirectory = file("${rootProject.layout.buildDirectory.get().asFile}/libs")
}

springBoot {
    mainClass = 'tgb.cryptoexchange.app.AppApplication'
}