plugins {
    id 'processing'
    id 'org.springframework.boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
}

tasks.named('bootJar') {
    archiveFileName = 'processing.jar'
    destinationDirectory = file("${rootProject.layout.buildDirectory.get().asFile}/libs")
}

springBoot {
    mainClass = 'net.rcetech.app.AppApplication'
}