plugins {
    id 'processing'
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':processing-api')
    implementation project(':processing-billing')
    implementation project(':processing-clients')
    implementation project(':processing-orders')
    implementation project(':processing-support')
}

tasks.named('bootJar') {
    archiveFileName = 'processing.jar'
    destinationDirectory = file("${rootProject.layout.buildDirectory.get().asFile}/libs")
}

springBoot {
    mainClass = 'net.rcetech.app.AppApplication'
}