plugins {
    id 'processing'
}

dependencies {
    api project(':processing-clients-api')
    api project(':processing-orders-api')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation("org.springframework.boot:spring-boot-starter-aspectj")

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.0'


    implementation platform("org.springframework.grpc:spring-grpc-dependencies:1.0.3")
    implementation 'org.springframework.grpc:spring-grpc-spring-boot-starter'
    implementation 'build.buf:protovalidate:1.2.2'
    protobuf files('build.buf:protovalidate:1.2.2')

    implementation 'tgb.cryptoexchange:common-api:1.1.0'
    implementation 'tgb.cryptoexchange:commons:1.0'

    implementation 'com.fasterxml.uuid:java-uuid-generator:5.2.0'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    compileOnly 'jakarta.annotation:jakarta.annotation-api:3.0.0'


    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

idea {
    module {
        def generatedProtoDir = file("${projectDir}/build/generated/source/proto/main/java")

        sourceDirs += generatedProtoDir
        generatedSourceDirs += generatedProtoDir
    }
}
