plugins {
    id 'java-library'
    id 'processing'
    id 'com.google.protobuf'
    id 'idea'
}

dependencies {
    implementation project(':processing-meta')
    implementation project(':processing-orders')
    implementation project(':processing-clients')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-aspectj'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-security'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.0'

    implementation platform('org.springframework.grpc:spring-grpc-dependencies:1.0.3')
    implementation 'org.springframework.grpc:spring-grpc-spring-boot-starter'
    implementation 'build.buf:protovalidate:1.2.2'
    protobuf files('build.buf:protovalidate:1.2.2')

    implementation 'tgb.cryptoexchange:common-api:1.1.0'

    implementation 'com.fasterxml.uuid:java-uuid-generator:5.2.0'
}

idea {
    module {
        def generatedProtoDir = file("${projectDir}/build/generated/source/proto/main/java")

        sourceDirs += generatedProtoDir
        generatedSourceDirs += generatedProtoDir
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:4.34.1"
    }
    plugins {
        grpc {
            setArtifact("io.grpc:protoc-gen-grpc-java:1.81.0")
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                grpc {
                    option 'jakarta_omit'
                }
            }
        }
    }
}

bootJar {
    enabled = false
}
