plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
}

dependencies {
    implementation 'org.springframework.boot:org.springframework.boot.gradle.plugin:4.1.0'
    implementation 'io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.1.7'
    implementation 'com.google.protobuf:protobuf-gradle-plugin:0.10.0'
}