plugins {
    id 'processing'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway-server-webflux'

    implementation platform("org.springframework.grpc:spring-grpc-dependencies:1.0.3")
    implementation 'org.springframework.grpc:spring-grpc-spring-boot-starter'
    implementation 'build.buf:protovalidate:1.2.2'
    protobuf files('build.buf:protovalidate:1.2.2')

    implementation 'commons-codec:commons-codec:1.18.0'
    implementation 'io.jsonwebtoken:jjwt:0.13.0'

    api 'tgb.cryptoexchange:common-api:1.1.0'

    implementation 'tgb.cryptoexchange:commons:1.0'
    implementation 'com.fasterxml.uuid:java-uuid-generator:5.2.0'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    compileOnly 'jakarta.annotation:jakarta.annotation-api:3.0.0'

    testImplementation 'org.wiremock.integrations:wiremock-spring-boot:4.2.1'
    testImplementation 'org.springframework.boot:spring-boot-webtestclient'
    testImplementation 'org.springframework.grpc:spring-grpc-test'
    testImplementation 'io.grpc:grpc-testing'
    testImplementation 'org.testcontainers:junit-jupiter:1.21.4'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testImplementation 'io.projectreactor:reactor-test'
}

idea {
    module {
        sourceDirs += file("${projectDir}/build/extracted-include-protos/main")
        generatedSourceDirs += file("${projectDir}/build/extracted-include-protos/main")
    }
}