syntax = "proto3";

option java_package = "tgb.cryptoexchange.grpc.generated";
option java_multiple_files = true;

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";
import "buf/validate/validate.proto";

/**
 * Сервис обеспечивает регистрацию новых клиентов и получение по API-ключам.
 */
service ClientsService {

  /**
  * Метод получения клиента по его идентификатору.
  * При отсутствии клиента возвращает gRPC-код NOT_FOUND_VALUE (Код 5).
  */
  rpc GetClientById (GetClientByIdGrpc) returns (GetClientByIdResponseGrpc);
  /**
  * Запрос на создание цифровой подписи данных.
  */
  rpc CreateSignature (CreateSignatureGrpc) returns (CreateSignatureResponseGrpc);
}

message GetClientByIdGrpc {
  int64 id = 1 [(buf.validate.field).int64.gt = 0];
}

message GetClientByIdResponseGrpc {
  int64 id = 1;
  string username = 2;
  string api_key_preview = 3;
  google.protobuf.Timestamp registered_at = 4;
  string status = 5;
  string callback_url = 6;
  int32 order_timeout_seconds = 7;
}

message CreateSignatureGrpc{
  int64 client_id = 1 [(buf.validate.field).int64.gt = 0];
  string data = 2 [(buf.validate.field).string.min_len = 1];
}

message CreateSignatureResponseGrpc{
  string signature = 1;
}
